services:
  mysql:
    build:
      dockerfile: database/database.Dockerfile
    container_name: databaseContainer
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - databaseVolume:/var/lib/mysql
    networks:
      - examenInternal

  backend:
    build:
      dockerfile: backend/backend.Dockerfile
    container_name: backendContainer
    ports:
      - '8080:80'
    depends_on:
      - mysql
    networks:
      - examenInternal

  frontend:
    build:
      dockerfile: frontend/frontend.Dockerfile
    container_name: frontendContainer
    ports:
      - '8000:80'
    depends_on:
      - backend

volumes:
  databaseVolume:

networks:
  examenInternal:
